services:
  postgres_db:
    image: postgres:16

    ports:
      - "5432:5432"
    user: postgres
    environment:
      - POSTGRES_PASSWORD=postgres

    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres_db
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  postgres_data:
